name: Build

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches: 
      - master
      - dev

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Switch to Rust nightly
      run: rustup default nightly

    - name: Install Rustup components
      run: rustup component add llvm-tools-preview rust-src

    - name: Install QEMU
      run: sudo apt update && sudo apt install qemu-system-x86

    - name: Build runner
      run: cargo build -p kernel_runner --release

    - name: Check for warnings
      run: cargo xbuild --release --verbose
      env:
        RUSTFLAGS: -D warnings

    - name: Run tests
      run: cargo xtest --verbose
