name: Unit and Integration tests CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches: 
      - master
      - dev

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Switch to Rust nightly
      run: rustup default nightly

    - name: Install Rustup Components
      run: rustup component add rust-src llvm-tools-preview

    - name: Install xbuild and binutils
      run: cargo install cargo-xbuild cargo-binutils

    - name: Install QEMU, Nasm
      run: sudo apt update && sudo apt install qemu-system-x86 nasm

    - name: Check for warnings
      run: cargo xbuild --verbose
      env:
        RUSTFLAGS: -D warnings

    - name: Run tests
      run: cargo xtest --verbose
